//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuildProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Release|x86&quot;.
        /// </summary>
        internal static string BuildConfig {
            get {
                return ResourceManager.GetString("BuildConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        internal static string BuildConfig2005 {
            get {
                return ResourceManager.GetString("BuildConfig2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /project &quot;{0}&quot; /projectconfig {1}.
        /// </summary>
        internal static string BuildProjectCmd {
            get {
                return ResourceManager.GetString("BuildProjectCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to devenv &quot;{0}&quot; /rebuild {1} .
        /// </summary>
        internal static string BuildSolutionCmd {
            get {
                return ResourceManager.GetString("BuildSolutionCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\.
        /// </summary>
        internal static string DevenvFolder {
            get {
                return ResourceManager.GetString("DevenvFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Program Files (x86)\Microsoft Visual Studio 8\Common7\IDE.
        /// </summary>
        internal static string DevenvFolder2005 {
            get {
                return ResourceManager.GetString("DevenvFolder2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE.
        /// </summary>
        internal static string DevenvFolder2008 {
            get {
                return ResourceManager.GetString("DevenvFolder2008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE.
        /// </summary>
        internal static string DevenvFolder2010 {
            get {
                return ResourceManager.GetString("DevenvFolder2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\.
        /// </summary>
        internal static string DevenvFolder2012 {
            get {
                return ResourceManager.GetString("DevenvFolder2012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \bin\Release.
        /// </summary>
        internal static string SetupProjOriginalOutput {
            get {
                return ResourceManager.GetString("SetupProjOriginalOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Release.
        /// </summary>
        internal static string SetupProjOriginalOutput2005 {
            get {
                return ResourceManager.GetString("SetupProjOriginalOutput2005", resourceCulture);
            }
        }
    }
}
