//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///&lt;td width=&quot;15%&quot; rowspan = &quot;{6}&quot;&gt;{0}&lt;/td&gt;
        ///&lt;td width=&quot;8%&quot; rowspan = &quot;{6}&quot;&gt;{1}&lt;/td&gt;
        ///&lt;td width=&quot;1%&quot;&gt;{2}&lt;/td&gt;
        ///&lt;td width=&quot;7%&quot;&gt;{3}&lt;/td&gt;
        ///&lt;td width=&quot;17%&quot;&gt;{4}&lt;/td&gt;
        ///&lt;td width=&quot;13%&quot;&gt;{5}&lt;/td&gt;
        ///&lt;/tr&gt;
        ///.
        /// </summary>
        internal static string FirstRowMerge {
            get {
                return ResourceManager.GetString("FirstRowMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;tr&gt;
        ///&lt;td width=&quot;39%&quot; rowspan = &quot;{7}&quot;&gt;{0}&lt;/td&gt;
        ///&lt;td width=&quot;15%&quot;&gt;{1}&lt;/td&gt;
        ///&lt;td width=&quot;8%&quot;&gt;{2}&lt;/td&gt;
        ///&lt;td width=&quot;1%&quot;&gt;{3}&lt;/td&gt;
        ///&lt;td width=&quot;7%&quot;&gt;{4}&lt;/td&gt;
        ///&lt;td width=&quot;17%&quot;&gt;{5}&lt;/td&gt;
        ///&lt;td width=&quot;13%&quot;&gt;{6}&lt;/td&gt;
        ///&lt;/tr&gt;
        ///.
        /// </summary>
        internal static string MergeThree {
            get {
                return ResourceManager.GetString("MergeThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;tr&gt;
        ///&lt;td width=&quot;1%&quot;&gt;{0}&lt;/td&gt;
        ///&lt;td width=&quot;7%&quot;&gt;{1}&lt;/td&gt;
        ///&lt;td width=&quot;17%&quot;&gt;{2}&lt;/td&gt;
        ///&lt;td width=&quot;13%&quot;&gt;{3}&lt;/td&gt;
        ///&lt;/tr&gt;
        ///.
        /// </summary>
        internal static string ReportHistoryContent {
            get {
                return ResourceManager.GetString("ReportHistoryContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=MsoNormal&gt;&lt;b&gt;&lt;i&gt;&lt;u&gt;&lt;span style=&apos;font-size:15.0pt&apos;&gt;File History&lt;o:p&gt;&lt;/o:p&gt;&lt;/span&gt;&lt;/u&gt;&lt;/i&gt;&lt;/b&gt;&lt;/p&gt;
        ///
        ///&lt;table id = &quot;HistoryInfo&quot; border=&quot;1&quot; cellpadding=&quot;2&quot; cellspacing=&quot;0&quot; style=&quot;border-collapse: collapse; font-size: 9pt&quot; bordercolor=&quot;black&quot; width=&quot;100%&quot;&gt;
        ///&lt;tr&gt;
        ///    &lt;th width=&quot;39%&quot;&gt;File Location&lt;/th&gt;
        ///    &lt;th width=&quot;15%&quot;&gt;File Name&lt;/th&gt;
        ///    &lt;th width=&quot;8%&quot;&gt;Status&lt;/th&gt;   
        ///    &lt;th width=&quot;1%&quot;&gt;Revision&lt;/th&gt; 
        ///    &lt;th width=&quot;7%&quot;&gt;Author&lt;/th&gt;
        ///    &lt;th width=&quot;17%&quot;&gt;Comment&lt;/th&gt;
        ///    &lt;th width=&quot;13%&quot;&gt;Date&lt;/th&gt;   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReportHistoryFileColumnHeader {
            get {
                return ResourceManager.GetString("ReportHistoryFileColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;tr&gt;
        ///&lt;td width=&quot;39%&quot; rowspan = &quot;{7}&quot;&gt;{0}&lt;/td&gt;
        ///&lt;td width=&quot;15%&quot;&gt;{1}&lt;/td&gt;
        ///&lt;td width=&quot;8%&quot;&gt;{2}&lt;/td&gt;
        ///&lt;td width=&quot;1%&quot;&gt;{3}&lt;/td&gt;
        ///&lt;td width=&quot;7%&quot;&gt;{4}&lt;/td&gt;
        ///&lt;td width=&quot;17%&quot;&gt;{5}&lt;/td&gt;
        ///&lt;td width=&quot;13%&quot;&gt;{6}&lt;/td&gt;
        ///&lt;/tr&gt;
        ///.
        /// </summary>
        internal static string ReportHistoryFileContent {
            get {
                return ResourceManager.GetString("ReportHistoryFileContent", resourceCulture);
            }
        }
    }
}
