//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IESXiHelper")]
public interface IESXiHelper
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESXiHelper/PowerOnVM", ReplyAction="http://tempuri.org/IESXiHelper/PowerOnVMResponse")]
    bool PowerOnVM(string aHost, string aHostLogin, string aHostPwd, string aVMFile, string aSnapshot);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESXiHelper/PowerOffVM", ReplyAction="http://tempuri.org/IESXiHelper/PowerOffVMResponse")]
    bool PowerOffVM(string aHost, string aHostLogin, string aHostPwd, string aVMFile);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESXiHelper/GetSnapshotList", ReplyAction="http://tempuri.org/IESXiHelper/GetSnapshotListResponse")]
    string[] GetSnapshotList(string aHost, string aHostLogin, string aHostPwd, string aVMFile);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IESXiHelperChannel : IESXiHelper, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class ESXiHelperClient : System.ServiceModel.ClientBase<IESXiHelper>, IESXiHelper
{
    
    public ESXiHelperClient()
    {
    }
    
    public ESXiHelperClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ESXiHelperClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ESXiHelperClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ESXiHelperClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public bool PowerOnVM(string aHost, string aHostLogin, string aHostPwd, string aVMFile, string aSnapshot)
    {
        return base.Channel.PowerOnVM(aHost, aHostLogin, aHostPwd, aVMFile, aSnapshot);
    }
    
    public bool PowerOffVM(string aHost, string aHostLogin, string aHostPwd, string aVMFile)
    {
        return base.Channel.PowerOffVM(aHost, aHostLogin, aHostPwd, aVMFile);
    }
    
    public string[] GetSnapshotList(string aHost, string aHostLogin, string aHostPwd, string aVMFile)
    {
        return base.Channel.GetSnapshotList(aHost, aHostLogin, aHostPwd, aVMFile);
    }
}
